const KEY="radheFoundationDB_v2";
const DEMO={donations:[],donationNotices:[],expenses:[],services:[],campaigns:[],requests:[],settings:{qr:""}};
let db=loadDB();
function loadDB(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==="object"?{...DEMO,...x,settings:{...DEMO.settings,...(x.settings||{})}}:structuredClone(DEMO)}catch(e){return structuredClone(DEMO)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function money(n){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function uid(prefix){return prefix+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,7)}
function dateNow(){return new Date().toISOString().slice(0,10)}
function totals(){let d=db.donations.filter(x=>x.public!==false).reduce((a,x)=>a+Number(x.amount||0),0),e=db.expenses.reduce((a,x)=>a+Number(x.amount||0),0);return{d,e,b:d-e}}
function getImages(x){if(Array.isArray(x.images)&&x.images.length)return x.images;if(x.image)return[x.image];return[]}
let currentPublicTab="home";
let restoringPublicHistory=false;
function showPublicTab(name,fromHistory=false){
  const el=document.getElementById("public-"+name);
  if(!el)return;
  document.querySelectorAll(".public-panel").forEach(x=>x.classList.add("hidden"));
  el.classList.remove("hidden");
  currentPublicTab=name;
  if(!fromHistory&&!restoringPublicHistory){
    const state={type:"public",tab:name};
    if(!history.state||history.state.type!=="public"||history.state.tab!==name)history.pushState(state,"",location.href.split("#")[0]+"#"+name);
  }
  window.scrollTo({top:0,behavior:"smooth"});
}
function handleBackNavigation(){
  const admin=document.getElementById("adminModal"), help=document.getElementById("help247Modal"), donation=document.getElementById("donationNoticeModal"), edit=document.getElementById("editModal"), viewer=document.getElementById("photoViewer"), ds=document.getElementById("donationScreenshotViewer");
  if(ds&&!ds.classList.contains("hidden")){closeDonationScreenshot();return;}
  if(viewer&&!viewer.classList.contains("hidden")){closePhotoViewer();return;}
  if(edit&&!edit.classList.contains("hidden")){closeEditModal();return;}
  if(donation&&!donation.classList.contains("hidden")){closeDonationNotice();return;}
  if(help&&!help.classList.contains("hidden")){closeHelp247();return;}
  if(admin&&!admin.classList.contains("hidden")){closeAdmin();return;}
  const state=history.state;
  if(state&&state.type==="public"){restoringPublicHistory=true;showPublicTab(state.tab||"home",true);restoringPublicHistory=false;}
}
window.addEventListener("popstate",handleBackNavigation);

function renderAll(){const t=totals();document.getElementById("totalDonation").textContent=money(t.d);document.getElementById("totalExpense").textContent=money(t.e);document.getElementById("balance").textContent=money(t.b);document.getElementById("serviceCount").textContent=db.services.length;document.getElementById("year").textContent=new Date().getFullYear();renderDonors();renderCampaigns();renderExpenses();renderServices();renderQR();updateBadge();if(!document.getElementById("adminView").classList.contains("hidden"))renderAdmin()}
function empty(icon,msg){return`<div class="gallery-item"><div class="placeholder">${icon}</div><div class="pad">${msg}</div></div>`}
function renderDonors(){const rows=db.donations.filter(x=>x.public!==false).slice().reverse();document.getElementById("donorGrid").innerHTML=rows.map(x=>`<article class="donor-card">${x.photo?`<img class="donor-photo" src="${esc(x.photo)}" alt="${esc(x.name)}" onclick="openGenericPhoto('${x.id}','donation')" style="cursor:zoom-in">`:`<div class="donor-photo" style="display:grid;place-items:center;background:#eef2f7;font-size:35px">🙏</div>`}<h3>${esc(x.name)}</h3><div class="detail-line">📅 ${esc(x.date||"")}</div><div class="detail-line">💰 ${money(x.amount)}</div><div class="detail-line">🎯 ${esc(x.purpose||"-" )}</div></article>`).join("")||`<div class="detail-card">હજુ કોઈ જાહેર દાતાશ્રી નોંધાયેલ નથી.</div>`}
function renderCampaigns(){document.getElementById("campaignGrid").innerHTML=db.campaigns.slice().reverse().map(c=>{let p=Math.min(100,Math.round(Number(c.collected||0)/Math.max(1,Number(c.target||0))*100));const imgs=getImages(c);return`<article class="campaign">${imgs[0]?`<img class="gallery-photo" src="${esc(imgs[0])}" alt="${esc(c.title)}" onclick="openGenericPhoto('${c.id}','campaign')">`:""}<h3>${esc(c.title)}</h3><p>${esc(c.description||"")}</p><div class="progress"><span style="width:${p}%"></span></div><p><b>લક્ષ્ય: ${money(c.target)}</b><br><b>મળેલ: ${money(c.collected)}</b> (${p}%)</p>${imgs.length>1?`<small>📷 ${imgs.length} ફોટા</small>`:""}</article>`}).join("")||empty("📢","હજુ અભિયાન ઉમેરાયેલ નથી.")}
function renderExpenses(){document.getElementById("expenseGrid").innerHTML=db.expenses.slice().reverse().map(x=>{const imgs=getImages(x);return`<article class="detail-card">${imgs[0]?`<img class="gallery-photo" src="${esc(imgs[0])}" alt="${esc(x.title)}" onclick="openGenericPhoto('${x.id}','expense')">`:""}<h3>${esc(x.title)}</h3><div class="detail-line">💰 રકમ: <b>${money(x.amount)}</b></div><div class="detail-line">📅 તારીખ: ${esc(x.date||"")}</div><div class="detail-line">📂 કેટેગરી: ${esc(x.category||"")}</div><div class="detail-line">📍 સ્થળ: ${esc(x.place||"-" )}</div><div class="detail-line">📝 નોંધ: ${esc(x.note||"-" )}</div>${imgs.length>1?`<small>📷 ${imgs.length} ફોટા</small>`:""}</article>`}).join("")||`<div class="detail-card">હજુ કોઈ ખર્ચ નોંધાયેલ નથી.</div>`}
function serviceCard(x){const imgs=getImages(x);const first=imgs[0];return`<article class="gallery-item">${first?`<img class="gallery-photo" src="${esc(first)}" alt="${esc(x.title)}" onclick="openPhotoViewer('${x.id}',0)">`:`<div class="placeholder">🤝</div>`}<div class="pad"><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p><small>📅 ${esc(x.date||"")} ${x.amount?` • 💰 ${money(x.amount)}`:""}${imgs.length>1?` • 📷 ${imgs.length} ફોટા`:""}</small></div></article>`}
function renderServices(){const cards=db.services.slice().reverse().map(serviceCard).join("");document.getElementById("servicesGrid").innerHTML=cards||empty("📸","હજુ સેવા કાર્ય ઉમેરાયેલ નથી.");document.getElementById("galleryGrid").innerHTML=db.services.filter(x=>getImages(x).length).slice().reverse().map(serviceCard).join("")||empty("🖼️","હજુ તસવીરો ઉપલબ્ધ નથી.")}
function renderQR(){const box=document.getElementById("qrBox");box.innerHTML=db.settings.qr?`<img class="qr-image" src="${esc(db.settings.qr)}" alt="Donation QR" style="cursor:zoom-in" onclick="openGenericPhoto('qr','qr')">`:`<div class="placeholder qr-placeholder">QR</div>`}
function updateBadge(){const n=db.donationNotices.filter(x=>x.status!=="Approved").length;const b=document.getElementById("noticeBadge");if(b)b.textContent=n}
function openAdmin(){document.getElementById("adminModal").classList.remove("hidden");if(sessionStorage.getItem("rf_admin")==="1")showAdmin()}
function closeAdmin(){document.getElementById("adminModal").classList.add("hidden")}
document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();let u=document.getElementById("adminUser").value.trim(),p=document.getElementById("adminPass").value;if(u==="Radhe"&&p==="Krishna@11"){sessionStorage.setItem("rf_admin","1");showAdmin()}else document.getElementById("loginMsg").textContent="Username અથવા password ખોટો છે."})
function showAdmin(){document.getElementById("loginView").classList.add("hidden");document.getElementById("adminView").classList.remove("hidden");renderAdmin()}
function logout(){sessionStorage.removeItem("rf_admin");document.getElementById("adminView").classList.add("hidden");document.getElementById("loginView").classList.remove("hidden")}
function showTab(name){document.querySelectorAll(".admin-tab").forEach(x=>x.classList.add("hidden"));document.getElementById("tab-"+name).classList.remove("hidden")}
function renderAdmin(){const t=totals();document.getElementById("tab-overview").innerHTML=`<div class="admin-grid"><div class="mini">કુલ દાન<b>${money(t.d)}</b></div><div class="mini">કુલ ખર્ચ<b>${money(t.e)}</b></div><div class="mini">બેલેન્સ<b>${money(t.b)}</b></div><div class="mini">સેવા<b>${db.services.length}</b></div></div><div class="admin-form"><h3>ઝડપી નિકાસ</h3><p class="muted">ડેટાનો JSON backup સાચવો.</p><div class="row-actions"><button class="btn primary small" onclick="exportDB()">Export JSON</button><button class="btn small" onclick="seedDemo()">Demo Data</button><button class="btn danger small" onclick="clearDB()">બધો ડેટા સાફ કરો</button></div></div>`;document.getElementById("tab-donations").innerHTML=donationAdmin();document.getElementById("tab-donationNotices").innerHTML=donationNoticeAdmin();document.getElementById("tab-donorPhotos").innerHTML=donorAdmin();document.getElementById("tab-expenses").innerHTML=expenseAdmin();document.getElementById("tab-servicesTab").innerHTML=serviceAdmin();document.getElementById("tab-campaignsTab").innerHTML=campaignAdmin();document.getElementById("tab-requests").innerHTML=requestAdmin();document.getElementById("tab-settings").innerHTML=settingsAdmin()}
function donationAdmin(){return`<div class="admin-form"><h3>+ દાન ઉમેરો</h3><form onsubmit="addDonation(event)"><div class="grid2"><label>દાતાશ્રીનું નામ<input name="name" required></label><label>રકમ<input name="amount" type="number" min="1" required></label><label>તારીખ<input name="date" type="date" value="${dateNow()}" required></label><label>ઉદ્દેશ<input name="purpose" placeholder="શિક્ષણ / આરોગ્ય..."></label><label>દાતાશ્રીનો ફોટો<input name="photo" type="file" accept="image/*"></label></div><label><input name="public" type="checkbox" checked style="width:auto;margin-right:8px"> Publicમાં દાતાશ્રીનું નામ બતાવવું</label><button class="btn primary">સાચવો</button></form></div><h3>દાન Entries (${db.donations.length})</h3>${db.donations.slice().reverse().map(x=>`<div class="item-row"><div><b>${esc(x.name)}</b> — ${money(x.amount)}<br><small>${esc(x.date)} • ${esc(x.purpose||"")}</small></div><div class="row-actions"><button class="btn small" onclick="editDonation('${x.id}')">Edit</button><button class="btn danger small" onclick="removeItem('donations','${x.id}')">Delete</button></div></div>`).join("")||"<p>કોઈ Entry નથી.</p>"}`}
function donationNoticeAdmin(){return`<h3>દાનની જાણ (${db.donationNotices.length})</h3>${db.donationNotices.slice().reverse().map(x=>`<div class="admin-form ${x.status==='Approved'?'approved-box':x.status==='Failed'?'failed-box':'pending-box'}"><div class="item-row"><div><b>${esc(x.name)}</b> • ${money(x.amount)}<br><small>📍 ${esc(x.village)} • 📱 ${esc(x.phone)} • ${esc(x.date)} • <span class="status ${x.status==='Approved'?'approved':x.status==='Failed'?'failed':'pending'}">${esc(x.status||'Pending')}</span></small></div><div class="row-actions"><button class="btn small" onclick="editDonationNotice('${x.id}')">Edit</button><button class="btn danger small" onclick="removeItem('donationNotices','${x.id}')">Delete</button></div></div>${x.screenshot?`<button class="notice-image-button" type="button" onclick="openDonationScreenshot('${x.id}')"><img class="notice-thumb" src="${esc(x.screenshot)}" alt="Payment screenshot"><span>સ્ક્રીનશોટ જુઓ / Zoom</span></button>`:""}<p>${esc(x.details||"")}</p><div class="donation-status-row"><label>દાનનો Status<select id="donation-status-${x.id}"><option value="Pending" ${x.status==='Pending'||!x.status?'selected':''}>Pending</option><option value="Approved" ${x.status==='Approved'?'selected':''}>Approve</option><option value="Failed" ${x.status==='Failed'?'selected':''}>Fail</option></select></label><button class="btn primary small" onclick="saveDonationNoticeStatus('${x.id}')">Save</button></div></div>`).join("")||"<p>હજુ દાનની કોઈ જાણ નથી.</p>"}`}
function donorAdmin(){return`<div class="admin-form"><h3>દાતાશ્રીઓ</h3><p class="muted">દાતાશ્રીના ફોટા અને જાહેર દર્શનનું Edit અહીંથી કરો.</p>${db.donations.slice().reverse().map(x=>`<div class="item-row"><div><b>${esc(x.name)}</b><br><small>${money(x.amount)} • ${esc(x.date)}</small></div><div class="row-actions"><button class="btn small" onclick="editDonation('${x.id}')">Edit</button><button class="btn danger small" onclick="removeItem('donations','${x.id}')">Delete</button></div></div>`).join("")||"<p>કોઈ દાતાશ્રી નથી.</p>"}</div>`}
function expenseAdmin(){return`<div class="admin-form"><h3>+ ખર્ચ ઉમેરો</h3><form onsubmit="addExpense(event)"><div class="grid2"><label>ખર્ચનું નામ<input name="title" required></label><label>રકમ<input name="amount" type="number" min="1" required></label><label>તારીખ<input name="date" type="date" value="${dateNow()}" required></label><label>કેટેગરી<select name="category"><option>શિક્ષણ</option><option>આરોગ્ય</option><option>પરિવાર સહાય</option><option>આપત્તિ રાહત</option><option>અન્ય</option></select></label><label>સ્થળ<input name="place" required></label><label>નોંધ<input name="note"></label><label>ફોટા<input name="images" type="file" accept="image/*" multiple></label></div><button class="btn primary">સાચવો</button></form></div><h3>ખર્ચ Entries (${db.expenses.length})</h3>${db.expenses.slice().reverse().map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b> — ${money(x.amount)}<br><small>${esc(x.date)} • ${esc(x.category)} • ${esc(x.place||"")}</small></div><div class="row-actions"><button class="btn small" onclick="editExpense('${x.id}')">Edit</button><button class="btn danger small" onclick="removeItem('expenses','${x.id}')">Delete</button></div></div>`).join("")||"<p>કોઈ Entry નથી.</p>"}`}
function serviceAdmin(){return`<div class="admin-form"><h3>+ સેવા કાર્ય / ફોટા ઉમેરો</h3><form onsubmit="addService(event)"><div class="grid2"><label>શીર્ષક<input name="title" required></label><label>તારીખ<input name="date" type="date" value="${dateNow()}" required></label><label>ખર્ચ (વૈકલ્પિક)<input name="amount" type="number" min="0"></label><label>ફોટા<input name="images" type="file" accept="image/*" multiple></label></div><label>વિગત<textarea name="description" rows="3"></textarea></label><button class="btn primary">સાચવો</button></form></div><h3>સેવા Entries (${db.services.length})</h3>${db.services.slice().reverse().map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b><br><small>${esc(x.date)} ${x.amount?`• ${money(x.amount)}`:""} • ${getImages(x).length} ફોટા</small></div><div class="row-actions"><button class="btn small" onclick="editService('${x.id}')">Edit</button><button class="btn danger small" onclick="removeItem('services','${x.id}')">Delete</button></div></div>`).join("")||"<p>કોઈ Entry નથી.</p>"}`}
function campaignAdmin(){return`<div class="admin-form"><h3>+ અભિયાન ઉમેરો</h3><form onsubmit="addCampaign(event)"><div class="grid2"><label>અભિયાનનું નામ<input name="title" required></label><label>લક્ષ્ય રકમ<input name="target" type="number" min="1" required></label><label>મળેલી રકમ<input name="collected" type="number" min="0" value="0"></label><label>ફોટા<input name="images" type="file" accept="image/*" multiple></label></div><label>વિગત<textarea name="description"></textarea></label><button class="btn primary">સાચવો</button></form></div><h3>અભિયાન Entries (${db.campaigns.length})</h3>${db.campaigns.map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b> — લક્ષ્ય ${money(x.target)} • મળેલ ${money(x.collected)}</div><div class="row-actions"><button class="btn small" onclick="editCampaign('${x.id}')">Edit</button><button class="btn danger small" onclick="removeItem('campaigns','${x.id}')">Delete</button></div></div>`).join("")||"<p>કોઈ Entry નથી.</p>"}`}
function requestAdmin(){return`<h3>સહાય અરજીઓ (${db.requests.length})</h3>${db.requests.slice().reverse().map(x=>`<div class="admin-form"><div class="item-row"><div><b>${esc(x.name)}</b> • ${esc(x.type)} • ${money(x.amount)}<br><small>📱 ${esc(x.phone)} • ✉️ ${esc(x.email)} • 📍 ${esc(x.village)} • ${esc(x.district)} / ${esc(x.taluka)} • ${esc(x.date)}</small></div><span class="status ${String(x.status||'Pending').toLowerCase().replace(/ /g,'-')}">${esc(x.status)}</span></div><p>${esc(x.details)}</p><div class="edit-grid"><label>Status<select id="req-status-${x.id}"><option ${x.status==='Pending'?'selected':''}>Pending</option><option ${x.status==='Under Review'?'selected':''}>Under Review</option><option ${x.status==='Approved'?'selected':''}>Approved</option><option ${x.status==='Assistance Given'?'selected':''}>Assistance Given</option><option ${x.status==='Closed'?'selected':''}>Closed</option></select></label><label>Admin નોંધ<textarea id="req-note-${x.id}" rows="2">${esc(x.adminNote||"")}</textarea></label></div><button class="btn primary small" onclick="saveRequest('${x.id}')">Save & Update</button></div>`).join("")||"<p>કોઈ અરજી નથી.</p>"}`}
function settingsAdmin(){return`<div class="admin-form"><h3>દાન QR અપડેટ</h3><form onsubmit="saveQR(event)"><label>QR Code<input name="qr" type="file" accept="image/*"></label><button class="btn primary">Save QR</button></form>${db.settings.qr?`<div class="donate-box"><img class="qr-image" src="${esc(db.settings.qr)}" alt="Current QR"><button class="btn danger" onclick="removeQR()">Delete QR</button></div>`:"<p>હજુ QR ઉમેરાયેલ નથી.</p>"}</div>`}
function formObj(e){return Object.fromEntries(new FormData(e.target).entries())}
function readFile(file){return new Promise((resolve,reject)=>{if(!file)return resolve("");const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function addDonation(e){e.preventDefault();const f=formObj(e),photo=await readFile(e.target.photo.files[0]);db.donations.push({id:uid("DON"),name:f.name,amount:+f.amount,date:f.date,purpose:f.purpose||"",public:f.public==="on",photo});save();e.target.reset();showTab("donations")}
async function addExpense(e){e.preventDefault();let f=formObj(e),files=Array.from(e.target.images?.files||[]),images=[];for(const file of files){if(file.size>4*1024*1024){alert("દરેક ફોટો 4MBથી નાનો રાખો.");return}images.push(await readFile(file))}db.expenses.push({id:uid("EXP"),...f,amount:+f.amount,images,image:images[0]||""});save();e.target.reset();showTab("expenses")}
async function addCampaign(e){e.preventDefault();let f=formObj(e),files=Array.from(e.target.images?.files||[]),images=[];for(const file of files){if(file.size>4*1024*1024){alert("દરેક ફોટો 4MBથી નાનો રાખો.");return}images.push(await readFile(file))}db.campaigns.push({id:uid("CAM"),...f,target:+f.target,collected:+f.collected,images,image:images[0]||""});save();e.target.reset();showTab("campaignsTab")}
async function addService(e){e.preventDefault();let f=formObj(e),files=Array.from(e.target.images.files||[]);for(const file of files)if(file.size>4*1024*1024){alert("દરેક ફોટો 4MBથી નાનો રાખો.");return}const images=[];for(const file of files)images.push(await readFile(file));db.services.push({id:uid("SRV"),title:f.title,date:f.date,amount:+(f.amount||0),description:f.description||"",images,image:images[0]||""});save();e.target.reset();showTab("servicesTab")}
async function saveQR(e){e.preventDefault();const file=e.target.qr.files[0];if(!file){alert("QR ફોટો પસંદ કરો.");return}db.settings.qr=await readFile(file);save();showTab("settings")}
function removeQR(){if(confirm("QR delete કરવો છે?")){db.settings.qr="";save();showTab("settings")}}
function removeItem(type,id){if(confirm("આ Entry delete કરવી છે?")){db[type]=db[type].filter(x=>x.id!==id);save()}}
function editDonation(id){const x=db.donations.find(x=>x.id===id);if(!x)return;openEditModal("દાતાશ્રી Edit",`<form id="editForm"><div class="grid2"><label>નામ<input name="name" value="${esc(x.name)}" required></label><label>રકમ<input name="amount" type="number" value="${x.amount}" required></label><label>તારીખ<input name="date" type="date" value="${esc(x.date)}" required></label><label>ઉદ્દેશ<input name="purpose" value="${esc(x.purpose||"")}"></label><label>ફોટો<input name="photo" type="file" accept="image/*"></label></div><label><input name="public" type="checkbox" ${x.public!==false?'checked':''} style="width:auto;margin-right:8px"> Publicમાં બતાવવું</label><button class="btn primary">Save</button></form>`,async e=>{e.preventDefault();const f=formObj(e),photo=await readFile(e.target.photo.files[0]);Object.assign(x,{name:f.name,amount:+f.amount,date:f.date,purpose:f.purpose||"",public:f.public==="on",photo:photo||x.photo||""});closeEditModal();save();showTab("donations")})}
function editExpense(id){const x=db.expenses.find(x=>x.id===id);if(!x)return;openEditModal("ખર્ચ Edit",`<form id="editForm"><div class="grid2"><label>નામ<input name="title" value="${esc(x.title)}" required></label><label>રકમ<input name="amount" type="number" value="${x.amount}" required></label><label>તારીખ<input name="date" type="date" value="${esc(x.date)}" required></label><label>કેટેગરી<input name="category" value="${esc(x.category)}" required></label><label>સ્થળ<input name="place" value="${esc(x.place||"")}" required></label><label>નોંધ<input name="note" value="${esc(x.note||"")}"></label><label>નવા ફોટા<input name="images" type="file" accept="image/*" multiple></label></div><button class="btn primary">Save</button></form>`,async e=>{e.preventDefault();const f=formObj(e),files=Array.from(e.target.images?.files||[]),imgs=[];for(const file of files){if(file.size>4*1024*1024){alert("દરેક ફોટો 4MBથી નાનો રાખો.");return}imgs.push(await readFile(file))}Object.assign(x,{title:f.title,amount:+f.amount,date:f.date,category:f.category,place:f.place,note:f.note,...(imgs.length?{images:imgs,image:imgs[0]}:{})});closeEditModal();save();showTab("expenses")})}
function editCampaign(id){const x=db.campaigns.find(x=>x.id===id);if(!x)return;openEditModal("અભિયાન Edit",`<form id="editForm"><label>નામ<input name="title" value="${esc(x.title)}" required></label><div class="grid2"><label>લક્ષ્ય રકમ<input name="target" type="number" value="${x.target}" required></label><label>મળેલી રકમ<input name="collected" type="number" value="${x.collected}" required></label><label>નવા ફોટા<input name="images" type="file" accept="image/*" multiple></label></div><label>વિગત<textarea name="description">${esc(x.description||"")}</textarea></label><button class="btn primary">Save</button></form>`,async e=>{e.preventDefault();const f=formObj(e),files=Array.from(e.target.images?.files||[]),imgs=[];for(const file of files){if(file.size>4*1024*1024){alert("દરેક ફોટો 4MBથી નાનો રાખો.");return}imgs.push(await readFile(file))}Object.assign(x,{title:f.title,target:+f.target,collected:+f.collected,description:f.description,...(imgs.length?{images:imgs,image:imgs[0]}:{})});closeEditModal();save();showTab("campaignsTab")})}
function editService(id){const x=db.services.find(x=>x.id===id);if(!x)return;openEditModal("સેવા Edit",`<form id="editForm"><div class="grid2"><label>શીર્ષક<input name="title" value="${esc(x.title)}" required></label><label>તારીખ<input name="date" type="date" value="${esc(x.date)}" required></label><label>ખર્ચ<input name="amount" type="number" value="${x.amount||0}"></label><label>નવા ફોટા<input name="images" type="file" accept="image/*" multiple></label></div><label>વિગત<textarea name="description">${esc(x.description||"")}</textarea></label><button class="btn primary">Save</button></form>`,async e=>{e.preventDefault();const f=formObj(e),files=Array.from(e.target.images.files||[]);const imgs=[];for(const file of files){if(file.size>4*1024*1024){alert("દરેક ફોટો 4MBથી નાનો રાખો.");return}imgs.push(await readFile(file))}Object.assign(x,{title:f.title,date:f.date,amount:+(f.amount||0),description:f.description||"",...(imgs.length?{images:imgs,image:imgs[0]}:{})});closeEditModal();save();showTab("servicesTab")})}
function editDonationNotice(id){const x=db.donationNotices.find(x=>x.id===id);if(!x)return;openEditModal("દાનની જાણ Edit",`<form id="editForm"><div class="grid2"><label>નામ<input name="name" value="${esc(x.name)}" required></label><label>ગામ<input name="village" value="${esc(x.village)}" required></label><label>મોબાઇલ<input name="phone" value="${esc(x.phone)}" required></label><label>રકમ<input name="amount" type="number" value="${x.amount}" required></label></div><label>વિગત<textarea name="details">${esc(x.details||"")}</textarea></label><button class="btn primary">Save</button></form>`,e=>{e.preventDefault();const f=formObj(e);Object.assign(x,{name:f.name,village:f.village,phone:f.phone,amount:+f.amount,details:f.details});closeEditModal();save();showTab("donationNotices")})}
function saveDonationNoticeStatus(id){const x=db.donationNotices.find(x=>x.id===id);if(!x)return;const status=document.getElementById("donation-status-"+id).value;x.status=status;if(status==="Approved"){x.approvedDate=dateNow();const exists=db.donations.find(d=>d.sourceNoticeId===x.id);if(!exists)db.donations.push({id:uid("DON"),name:x.name,amount:x.amount,date:x.date,purpose:"Online Donation",public:true,photo:"",sourceNoticeId:x.id});}else{db.donations=db.donations.filter(d=>d.sourceNoticeId!==x.id);}save();showTab("donationNotices");if(status==="Approved")sendApprovalEmail(x).catch(()=>{})}
function approveDonationNotice(id){saveDonationNoticeStatus(id)}
function openDonationScreenshot(id){const x=db.donationNotices.find(n=>n.id===id);if(!x||!x.screenshot)return;let m=document.getElementById("donationScreenshotViewer");if(!m){m=document.createElement("div");m.id="donationScreenshotViewer";m.className="modal donation-screenshot-viewer";m.innerHTML=`<button class="photo-close" type="button" onclick="closeDonationScreenshot()">×</button><div class="donation-screenshot-stage"><img id="donationScreenshotImage" src="" alt="Payment screenshot"><div class="zoom-controls"><button type="button" onclick="zoomDonationScreenshot(-1)">−</button><button type="button" onclick="resetDonationScreenshotZoom()">100%</button><button type="button" onclick="zoomDonationScreenshot(1)">+</button></div></div>`;document.body.appendChild(m);const img2=document.getElementById("donationScreenshotImage");img2.addEventListener("wheel",e=>{e.preventDefault();zoomDonationScreenshot(e.deltaY<0?1:-1)},{passive:false});let pinch=0;img2.addEventListener("touchstart",e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});img2.addEventListener("touchmove",e=>{if(e.touches.length===2){e.preventDefault();const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch){window.donationScreenshotZoom=Math.max(.5,Math.min(4,(window.donationScreenshotZoom||1)+(d-pinch)/350));pinch=d;img2.style.transform=`scale(${window.donationScreenshotZoom})`}}},{passive:false})}m.classList.remove("hidden");const img=document.getElementById("donationScreenshotImage");img.src=x.screenshot;img.style.transform="scale(1)";document.body.style.overflow="hidden";window.donationScreenshotZoom=1}
function zoomDonationScreenshot(dir){const img=document.getElementById("donationScreenshotImage");if(!img)return;window.donationScreenshotZoom=Math.min(4,Math.max(.5,(window.donationScreenshotZoom||1)+dir*.25));img.style.transform=`scale(${window.donationScreenshotZoom})`}
function resetDonationScreenshotZoom(){window.donationScreenshotZoom=1;const img=document.getElementById("donationScreenshotImage");if(img)img.style.transform="scale(1)"}
function closeDonationScreenshot(){const m=document.getElementById("donationScreenshotViewer");if(m)m.classList.add("hidden");document.body.style.overflow=""}
function saveRequest(id){const x=db.requests.find(x=>x.id===id);if(!x)return;const old=x.status;const status=document.getElementById("req-status-"+id).value;const note=document.getElementById("req-note-"+id).value;x.status=status;x.adminNote=note;x.updatedDate=dateNow();save();showTab("requests");if(status!==old&&(status==="Approved"||status==="Assistance Given"||status==="Closed"))sendApprovalEmail(x).catch(()=>{})}
async function sendApprovalEmail(x){const cfg=window.RF_CONFIG||{};if(cfg.emailApiUrl){await fetch(cfg.emailApiUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:x.email,name:x.name,status:x.status,subject:"RADHE FOUNDATION - અરજી અંગે માહિતી",message:`નમસ્તે ${x.name},\nતમારી RADHE FOUNDATION સહાય અરજીનો status: ${x.status}.\n${x.adminNote||""}`})});return}if(x.email){const subject=encodeURIComponent("RADHE FOUNDATION - અરજી અંગે માહિતી"),body=encodeURIComponent(`નમસ્તે ${x.name},\nતમારી RADHE FOUNDATION સહાય અરજીનો status: ${x.status}.\n${x.adminNote||""}`);window.open(`mailto:${encodeURIComponent(x.email)}?subject=${subject}&body=${body}`,"_blank")}}
function openDonationNotice(){document.getElementById("donationNoticeModal").classList.remove("hidden")}
function closeDonationNotice(){document.getElementById("donationNoticeModal").classList.add("hidden")}
document.getElementById("donationNoticeForm").addEventListener("submit",async e=>{e.preventDefault();const f=formObj(e),file=e.target.screenshot.files[0];if(!file){alert("Payment screenshot પસંદ કરો.");return}if(file.size>4*1024*1024){alert("Screenshot 4MBથી નાનો રાખો.");return}const screenshot=await readFile(file);db.donationNotices.push({id:uid("DN"),name:f.name,village:f.village,phone:f.phone,amount:+f.amount,screenshot,details:f.details||"",date:dateNow(),status:"Pending"});save();e.target.reset();document.getElementById("donationNoticeMsg").textContent="દાનની જાણ સફળતાપૂર્વક મોકલાઈ છે. આભાર.";setTimeout(closeDonationNotice,1000)})
function openEditModal(title,html,onSubmit){let m=document.getElementById("editModal");if(!m){m=document.createElement("div");m.id="editModal";m.className="modal hidden";document.body.appendChild(m)}m.innerHTML=`<div class="modal-box"><button class="close" onclick="closeEditModal()">×</button><span class="eyebrow">EDIT</span><h2>${esc(title)}</h2>${html}</div>`;m.classList.remove("hidden");const form=m.querySelector("#editForm");form.addEventListener("submit",onSubmit)}
function closeEditModal(){const m=document.getElementById("editModal");if(m)m.classList.add("hidden")}
let viewerServiceId="",viewerIndex=0,viewerZoom=1;
function openPhotoViewer(id,index=0){const x=db.services.find(s=>s.id===id);if(!x)return;const imgs=getImages(x);if(!imgs.length)return;window.genericPhotoList=null;viewerServiceId=id;viewerIndex=Math.max(0,Math.min(index,imgs.length-1));viewerZoom=1;document.getElementById("photoViewer").classList.remove("hidden");document.body.style.overflow="hidden";updatePhotoViewer()}
function updatePhotoViewer(){const x=db.services.find(s=>s.id===viewerServiceId);if(!x)return;const imgs=getImages(x);document.getElementById("viewerImage").src=imgs[viewerIndex];document.getElementById("viewerImage").style.transform=`scale(${viewerZoom})`;document.getElementById("photoCounter").textContent=`${viewerIndex+1} / ${imgs.length}`}
function changePhoto(dir){const x=db.services.find(s=>s.id===viewerServiceId);if(!x)return;const imgs=getImages(x);viewerIndex=(viewerIndex+dir+imgs.length)%imgs.length;viewerZoom=1;updatePhotoViewer()}
function zoomPhoto(dir){viewerZoom=Math.min(3,Math.max(.5,viewerZoom+dir*.25));updatePhotoViewer()}
function resetZoom(){viewerZoom=1;updatePhotoViewer()}
function closePhotoViewer(){document.getElementById("photoViewer").classList.add("hidden");document.body.style.overflow="";window.genericPhotoList=null;window.genericPhotoIndex=0;window.genericPhotoZoom=1}
document.addEventListener("keydown",e=>{const v=document.getElementById("photoViewer");if(v&&!v.classList.contains("hidden")){if(e.key==="Escape")closePhotoViewer();if(window.genericPhotoList){if(e.key==="ArrowLeft")genericPhotoChange(-1);if(e.key==="ArrowRight")genericPhotoChange(1);if(e.key==="+")genericPhotoZoom(1);if(e.key==="-")genericPhotoZoom(-1)}else{if(e.key==="ArrowLeft")changePhoto(-1);if(e.key==="ArrowRight")changePhoto(1);if(e.key==="+")zoomPhoto(1);if(e.key==="-")zoomPhoto(-1)}}})
let touchX=0;document.addEventListener("touchstart",e=>{const v=document.getElementById("photoViewer");if(v&&!v.classList.contains("hidden"))touchX=e.changedTouches[0].screenX},{passive:true});document.addEventListener("touchend",e=>{const v=document.getElementById("photoViewer");if(v&&!v.classList.contains("hidden")){const d=e.changedTouches[0].screenX-touchX;if(Math.abs(d)>50)changePhoto(d>0?-1:1)}},{passive:true})
function openGenericPhoto(id,type){let list=[];if(type==="donation"){const x=db.donations.find(v=>v.id===id);if(x?.photo)list=[{src:x.photo,caption:`${x.name} • ${money(x.amount)} • ${x.date||""}`}]}else if(type==="campaign"){const x=db.campaigns.find(v=>v.id===id);if(x)list=getImages(x).map(src=>({src,caption:`${x.title} • લક્ષ્ય ${money(x.target)} • મળેલ ${money(x.collected)}`}))}else if(type==="expense"){const x=db.expenses.find(v=>v.id===id);if(x)list=getImages(x).map(src=>({src,caption:`${x.title} • ${money(x.amount)} • ${x.date||""}`}))}else if(type==="qr"&&db.settings.qr)list=[{src:db.settings.qr,caption:"Donation QR"}];if(!list.length)return;openGenericPhotoList(list,0)}
function openGenericPhotoList(list,index=0){window.genericPhotoList=list;window.genericPhotoIndex=index;window.genericPhotoZoom=1;document.getElementById("photoViewer").classList.remove("hidden");document.body.style.overflow="hidden";renderGenericPhoto()}
function renderGenericPhoto(){const p=window.genericPhotoList[window.genericPhotoIndex];const img=document.getElementById("viewerImage");img.src=p.src;img.style.transform=`scale(${window.genericPhotoZoom||1})`;document.getElementById("photoCounter").textContent=`${window.genericPhotoIndex+1} / ${window.genericPhotoList.length}`;let cap=document.getElementById("photoCaption");if(!cap){cap=document.createElement("div");cap.id="photoCaption";cap.className="photo-caption";document.querySelector(".photo-stage").appendChild(cap)}cap.textContent=p.caption||""}
function genericPhotoChange(dir){const l=window.genericPhotoList||[];if(!l.length)return;window.genericPhotoIndex=(window.genericPhotoIndex+dir+l.length)%l.length;window.genericPhotoZoom=1;renderGenericPhoto()}
function genericPhotoZoom(dir){window.genericPhotoZoom=Math.min(4,Math.max(.5,(window.genericPhotoZoom||1)+dir*.25));renderGenericPhoto()}
function genericPhotoReset(){window.genericPhotoZoom=1;renderGenericPhoto()}
document.getElementById("viewerImage").addEventListener("wheel",e=>{if(!window.genericPhotoList)return;e.preventDefault();genericPhotoZoom(e.deltaY<0?1:-1)},{passive:false});
let genericPinchStart=0;document.getElementById("viewerImage").addEventListener("touchstart",e=>{if(e.touches.length===2)genericPinchStart=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});document.getElementById("viewerImage").addEventListener("touchmove",e=>{if(e.touches.length===2&&window.genericPhotoList){e.preventDefault();const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(genericPinchStart){window.genericPhotoZoom=Math.max(.5,Math.min(4,(window.genericPhotoZoom||1)+(d-genericPinchStart)/350));genericPinchStart=d;renderGenericPhoto()}}},{passive:false});
function exportDB(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="radhe-foundation-backup.json";a.click();URL.revokeObjectURL(a.href)}
function seedDemo(){if(!confirm("Demo data ઉમેરવું છે?"))return;db.donations.push({id:uid("DON"),name:"શ્રી દાતાશ્રી",amount:10000,date:dateNow(),purpose:"શિક્ષણ સહાય",public:true,photo:""});db.expenses.push({id:uid("EXP"),title:"વિદ્યાર્થી ફી સહાય",amount:4000,date:dateNow(),category:"શિક્ષણ",place:"સ્થાનિક શાળા",note:"Demo"});db.services.push({id:uid("SRV"),title:"વિદ્યાર્થી શિક્ષણ સહાય",date:dateNow(),amount:4000,description:"જરૂરિયાતમંદ વિદ્યાર્થીને ફી સહાય.",images:[],image:""});db.campaigns.push({id:uid("CAM"),title:"શિક્ષણ સહાય અભિયાન",target:50000,collected:10000,description:"જરૂરિયાતમંદ વિદ્યાર્થીઓ માટે."});save()}
function clearDB(){if(confirm("બધો Foundation data કાઢી નાખવો છે? આ ક્રિયા પાછી ફેરવી શકાશે નહીં.")){db=structuredClone(DEMO);save()}}
document.getElementById("helpForm").addEventListener("submit",e=>{e.preventDefault();const f=formObj(e);db.requests.push({id:uid("REQ"),...f,amount:+f.amount,date:dateNow(),status:"Pending",adminNote:""});save();e.target.reset();document.getElementById("helpMsg").textContent="તમારી અરજી સફળતાપૂર્વક મોકલાઈ છે. આભાર."})
if(!history.state||history.state.type!=="public"){history.replaceState({type:"public",tab:"home"},"",location.href.split("#")[0]+"#home");}
const initialTab=location.hash.replace(/^#/,"");
showPublicTab(document.getElementById("public-"+initialTab)?initialTab:"home",true);
renderAll();
